server:
  port: 8080
spring:
  application:
    name: social_media_backend
  datasource:
    url: jdbc:postgresql://nexo.postgres.database.azure.com:5432/nexo
    username: psqllocaladmin
    password: NoCountry.2025
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 675384024806-th1q5jkvv151qg8ac13c400v9nhkrkkt.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  cors:
    allowed-origins: http://localhost:5173